### ISSUE TITLE
inconsistent article count

### ISSUE THREAD

**Issue by koudyk** [jeromedockes/labelbuddy#18]
The article count is inconsistent between
- a) the number on the pop-up that tells you how many articles you've imported, and
- b) the number near the top-middle of the labelbuddy GUI (same number in the Annotate and Labels and Documents tabs)

**Comment by jeromedockes** [comment]
Thanks for reporting it! could you share the file you imported so I can
try to reproduce it? what were those numbers for you?

note (a) is the number of documents that have been added to your database
during the import operation and (b) is the total number of documents in
the database -- was the database empty before you imported your file?

**Comment by koudyk** [comment]
I can't seem to reproduce it. I think what might have happened is I might have  imported "420 annotations", and there are 421 documents. So I may have thought it was importing 420 documents because the numbers are so close.

sorry to have you investigate it for nothing!

Next time I'll try to replicate a problem right away so I can include how to replicate the problem in the issue

**Comment by jeromedockes** [comment]
no problem at all! thanks again!
