### ISSUE TITLE
[WONTFIX] also match different but similar-looking unicode characters when searching in document

### ISSUE THREAD

**Issue by koudyk** [jeromedockes/labelbuddy#20]
right now, I can only search a document below where I am in the document.
So if the word is above where I am, it looks like it isn't found.
Is there a way to make it so we can search above and below our current location?

**Comment by koudyk** [comment]
I can't reproduce the problem in other papers.
I think the problem is related to different types of dashes. 
e.g.,  A) "meta-ana" vs B) "meta‐ana"

in one paper (PMCID [7375078](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7375078)) , when I search for A, I get no results, but when I search for B, I find a bunch of results

**Comment by koudyk** [comment]
Trying to think of a solution for this (assuming it's a problem we want to solve). 

One solution would be to have pubget to convert all possible dashes to a single type of dash. 

Another solution would be to change the search functionality so when you search for one type of dash, it finds all types of dashes.

**Comment by jeromedockes** [comment]
re. searching above/below: the search wraps to the beginning if it reaches the end of the document. also we can search backwards by using shift+ctrl+f or shift+/ or the upwards pointing arrow next to the search box.

re matching similar-looking characters ( A) above is 0x2d, HYPHEN-MINUS whereas B) is 0x2010, HYPHEN) -- the search is a simple search for an exact match, which is fairly common -- for example libreoffice, google-chrome, and some text editors I tried also won't match "‐" when searching for "-" , although interestingly firefox does.

so I guess this could be useful but probably not enough to justify the added complexity. In particular it would require not relying on Qt's implementation of the search anymore (https://doc.qt.io/qt-6/qtextdocument.html#find)
